spring:
  datasource:
    url: ${DB_JDBC_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000
  sql:
    init:
      mode: always

  mail:
    host: smtp.office365.com
    port: 587
    username: gkswhdtn
    password: SKsk0424~o
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          #            required: true
          auth: true
          #          connectiontimeout: 5000
          #          timeout: 5000
          #          writetimeout: 5000

