server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/SKHUAZ
    username: root
    password: 12341234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
jwt:
  secret: secret-key
  token-validity-in-milliseconds: 86400000
  mail:
    host: smtp.naver.com #smtp ?? ??
    port: 465 # ?? ???? ??
    username: gjwldud0719 #??? ???
    password: jiyoung0343! #??? ????
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          #            required: true
          auth: true
          #          connectiontimeout: 5000
          #          timeout: 5000
          #          writetimeout: 5000
          ssl:
            trust: smtp.naver.com
            enable: true #??? ?? -> SSL ??? ?????